name: Build
on:
  workflow_dispatch:

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'ruleset.xml'
        #version: '7.0.0-SNAPSHOT'
        #downloadUrl: 'https://sourceforge.net/projects/pmd/files/pmd/7.0.0-SNAPSHOT/pmd-dist-7.0.0-SNAPSHOT-bin.zip/download'
