name: Build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pmd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    #- uses: pmd/pmd-github-action@v1
    #- uses: pmd/pmd-github-action@main
    #- uses: pmd/pmd-github-action@features/annotation
    - uses: adangel/pmd-github-action@support-pmd7-and-windows-paths
      id: pmd
      with:
        rulesets: 'ruleset.xml,category/java/design.xml/AbstractClassWithoutAnyMethod'
        version: '7.0.0-SNAPSHOT'
        downloadUrl: 'https://pmd-code.org/temp/pmd-bin-7.0.0-SNAPSHOT.zip'
