name: Build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pmd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    #- uses: pmd/pmd-github-action@v1
    #- uses: pmd/pmd-github-action@main
    #- uses: pmd/pmd-github-action@features/annotation
    #- uses: adangel/pmd-github-action@analyze-modified-files-only
    - uses: adangel/pmd-github-action@typescript
      id: pmd
      with:
        uploadSarifReport: ${{ runner.os == 'Linux' && 'true' || 'false' }}
        rulesets: 'ruleset.xml,category/java/design.xml/AbstractClassWithoutAnyMethod'
        version: '7.0.0-SNAPSHOT'
        downloadUrl: 'https://sourceforge.net/projects/pmd/files/pmd/7.0.0-SNAPSHOT/pmd-dist-7.0.0-SNAPSHOT-bin.zip/download'
