name: Build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: pmd/pmd-github-action@main
      id: pmd
      with:
        sourcePath: 'src/main/java'
        rulesets: 'ruleset.xml'
    - name: Fail build if there a violations
      if: steps.pmd.outputs.violations != 0
      run: exit 1
