name: Build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pmd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    #- uses: pmd/pmd-github-action@v1
    #- uses: pmd/pmd-github-action@main
    #- uses: pmd/pmd-github-action@features/annotation
    - uses: adangel/pmd-github-action@support-pmd7
      with:
        rulesets: 'ruleset.xml,category/apex/codestyle.xml/FieldNamingConventions'
        downloadUrl: 'https://sourceforge.net/projects/pmd/files/pmd/7.0.0-SNAPSHOT/pmd-bin-7.0.0-SNAPSHOT.zip/download'
